publish_mode: editorial_workflow
backend:
  name: github
  repo: kraussr/blog
  #base_url: https://30uf5tack8.execute-api.eu-central-1.amazonaws.com/prod/
  #auth_endpoint: /oauth/auth
site_id: kraussr.github.io
media_folder: "static/images" 
public_folder: "/images" 
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/blog"
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image", optional: true}
      - {label: "Featured image", name: "featured_image", widget: "image", optional: true}
      - {label: "Categories", name: "categories", widget: "list", default: ["news", "blog"]}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "post" # Used in routes, e.g., /admin/collections/blog
    label: "Articles" # Used in the UI
    folder: "content/post"
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Summary", name: "summary", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image", optional: true}
      - {label: "Featured image", name: "featured_image", widget: "image", optional: true}
      - {label: "Categories", name: "categories", widget: "list", default: ["articles"]}
      - {label: "Body", name: "body", widget: "markdown"}
